namespace inbox {
  # These mailboxes are widely used and could perhaps be created automatically:
  mailbox Drafts {
    special_use = \Drafts
    auto = subscribe
  }
mailbox Spam {
  special_use = \Junk
  auto = subscribe
}
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }

  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }
  
  mailbox Archive {
    special_use = \Archive
    auto = subscribe
  }
}
