service managesieve-login {
  inet_listener sieve {
    address = 127.0.0.1 ::1
    port = 4190
  }
}
service managesieve {
  process_limit = 1024
}

protocol sieve {
  # Refer to 90-sieve.conf for script quota configuration and configuration of
  # Sieve execution limits.
}
