Syslog                  yes
SyslogSuccess           yes
LogWhy                  no

# How strict the verification should be
Canonicalization        relaxed/simple
OversignHeaders         From

# Permissions
UserID                  opendkim:opendkim
UMask                   007

# Communication with Postfix
Socket                  inet:8891@localhost
PidFile                 /run/opendkim/opendkim.pid

# Operational reliability
AutoRestart             yes
AutoRestartRate         10/1h
Background              yes
DNSTimeout              5
SignatureAlgorithm      rsa-sha256

# Tables (This is the heart of your setup)
KeyTable                refile:/etc/opendkim/key.table
SigningTable            refile:/etc/opendkim/signing.table
ExternalIgnoreList      refile:/etc/opendkim/trusted.hosts
InternalHosts           refile:/etc/opendkim/trusted.hosts
