server:
  edns-buffer-size: 1232
  prefetch: yes
  prefetch-key: yes
  rrset-roundrobin: yes
  cache-min-ttl: 60
  cache-max-ttl: 86400
  infra-keep-probing: yes
  num-queries-per-thread: 512
  outgoing-range: 8192