server:
  cache-min-ttl: 60
  cache-max-negative-ttl: 60
  # DNSBL zones (they are not signed and should not give DNSSEC errors)
  domain-insecure: "spamhaus.org"
  domain-insecure: "surbl.org"
  domain-insecure: "dnswl.org"
  domain-insecure: "rspamd.com"
  domain-insecure: "senderscore.com"

  # Avoid unnecessary timeout errors
  infra-keep-probing: yes
  do-ip6: yes
  do-ip4: yes
  edns-buffer-size: 1232
  harden-glue: yes
  harden-dnssec-stripped: no

  # Increase timeouts (default 2s)
  num-queries-per-thread: 512
  outgoing-range: 8192
  infra-cache-numhosts: 10000
  delay-close: 5000